export const SET_START_DATE_TIME = 'SET_START_DATE_TIME'
export const SET_END_DATE_TIME = 'SET_END_DATE_TIME'
export const SET_ISVALID_DATE_TIME = 'SET_ISVALID_DATE_TIME'
export const SET_ISALWAYS_ON = 'SET_ISALWAYS_ON'
