export const SET_LINEITEM_PARTNER_DATA = 'SET_LINEITEM_PARTNER_DATA'
export const SET_CAMPAIGN_PARTNER_DATA = 'SET_CAMPAIGN_PARTNER_DATA'
export const SET_WALLET_PARTNER_DATA = 'SET_WALLET_PARTNER_DATA'
